=== Angel-L-G/Angel_DAD/xml/Act2/D2/Libro.dtd
<!-- DTD de libro -->
<!ELEMENT Libros (Libro+)>
<!ELEMENT Libro (Titulo, Contenido, Copyright)>
        <!ATTLIST Libro xmlns CDATA #REQUIRED >
    <!ELEMENT Titulo (#PCDATA)>
    <!ELEMENT Contenido ((Capitulo+, Separacion?)+)>
        <!ELEMENT Capitulo (Tema, Seccion+)>
                <!ATTLIST Capitulo materia (XML|Java) "Java" >
            <!ELEMENT Tema (#PCDATA)>
            <!ELEMENT Seccion (#PCDATA)>
                    <!ATTLIST Seccion apartados CDATA #REQUIRED>
                    <!ATTLIST Seccion dificil (si|no) "no" >
        <!ELEMENT Separacion EMPTY>
            <!ELEMENT Copyright (#PCDATA)>

=== Angel-L-G/Angel_DAD/xml/Act2/D2/Libro.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Libros SYSTEM "Libro.dtd">
<Libros>
    <Libro xmlns="1">
        <Titulo>Un titulo</Titulo>
        <Contenido>
            <Capitulo>
                <Tema></Tema>
                <Seccion apartados=""></Seccion>
                <Seccion apartados=""></Seccion>
            </Capitulo>
            <Capitulo>
                <Tema></Tema>
                <Seccion apartados=""></Seccion>
            </Capitulo>
        </Contenido>
        <Copyright>FreeWare</Copyright>
    </Libro>

    <Libro xmlns="1">
        <Titulo>Un titulo</Titulo>
        <Contenido>
            <Capitulo>
                <Tema></Tema>
                <Seccion apartados=""></Seccion>
                <Seccion apartados=""></Seccion>
            </Capitulo>
            <Separacion />
        </Contenido>
        <Copyright>FreeWare</Copyright>
    </Libro>
</Libros>
